CREATE TABLE IF NOT EXISTS team(
	id INT AUTO_INCREMENT PRIMARY KEY,
	nano_id VARCHAR(25) NOT NULL UNIQUE,
	team_name VARCHAR(60) NOT NULL UNIQUE,
	team_desc TEXT,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS esea_division(
	id TINYINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	division_name VARCHAR(15) NOT NULL UNIQUE,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

INSERT IGNORE INTO esea_division (id, division_name) 
	VALUES 
		(1, "Advanced"),
		(2, "Main"),
		(3, "Intermediate"),
		(4, "Entry"),
		(5, "Open"),
		(6, "None");

CREATE TABLE IF NOT EXISTS team_esea_division(
	id INT AUTO_INCREMENT PRIMARY KEY,
	team_id INT NOT NULL UNIQUE,
	esea_division TINYINT UNSIGNED NOT NULL,
	FOREIGN KEY (team_id) REFERENCES team(id),
	FOREIGN KEY (esea_division) REFERENCES esea_division(id),
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS team_achievements(
	id INT AUTO_INCREMENT PRIMARY KEY,
	team_id INT,
	event VARCHAR(32) NOT NULL,
	placement VARCHAR(10),
	details VARCHAR(120),
	date DATE NOT NULL,
	FOREIGN KEY (team_id) REFERENCES team(id),
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT UQ_TEAM_EVENT UNIQUE (team_id, event)
);

